/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package onion.poc;

public class DomainModel {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new DomainModel().getGreeting());
    }
}
