/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package onion.poc;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class DomainModelTest {
    @Test void appHasAGreeting() {
        DomainModel classUnderTest = new DomainModel();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
